language: java
before_install:
- openssl aes-256-cbc -K $encrypted_280827ea9045_key -iv $encrypted_280827ea9045_iv
  -in appinventor-ptpt-ed4e8cafcc91.json.enc -out appinventor/appinventor-ptpt-ed4e8cafcc91.json
  -d
- sudo apt-get -qq update
- sudo apt-get install -y libc6-i386 lib32stdc++6 lib32gcc1 lib32ncurses5 lib32z1
before_script: 
  - cd appinventor
  - wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 -O /tmp/phantomjs-2.1.1-linux-x86_64.tar.bz2
  - tar xfvj /tmp/phantomjs-2.1.1-linux-x86_64.tar.bz2
  - export PATH=$PATH:$PWD/phantomjs-2.1.1-linux-x86_64/bin
  - echo $PATH
script:
  - sed  -i  's/<\/title>/ - nr'$TRAVIS_BUILD_NUMBER' - '$TRAVIS_COMMIT'<\/title>/'   appengine/war/login.jsp
  - ant MakeAuthKey
  - ant
  - ant tests
before_deploy:
  - wget https://storage.googleapis.com/appengine-sdks/featured/appengine-java-sdk-1.9.48.zip -O /tmp/gae-sdk.zip
  - unzip /tmp/gae-sdk.zip
deploy:
  skip_cleanup: true
  provider: script
  script: ./appengine-java-sdk-1.9.48/bin/appcfg.sh -A appinventor-ptpt --service_account_json_key_file=appinventor-ptpt-ed4e8cafcc91.json update appengine/build/war/
  on:
    branch: master
