name: Build_Docker_Image

# Only triggered manually, and works only for feature/no-ref/ekalavya branch
on:
  workflow_dispatch:

env:
  TAG: dev

jobs:
  build-and-push:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 'Set up JDK 11'
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 11
      - name: 'Checkout submodules'
        run: git submodule update --init --recursive
      - name: 'Install 32-bit dependencies'
        run: sudo apt-get install -y libc6-i386 lib32z1 lib32stdc++6
      - name: 'Download phantomJS'
        run: |
          mkdir /tmp/phantomJS
          wget -P /tmp/phantomJS/ https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
      - name: 'Untar and add to PATH'
        run: |
          tar -xf /tmp/phantomJS/phantomjs-2.1.1-linux-x86_64.tar.bz2 -C /tmp/phantomJS/
          echo '/tmp/phantomJS/phantomjs-2.1.1-linux-x86_64/bin' >> $GITHUB_PATH
      - name: 'Make Auth Key'
        run: ant MakeAuthKey
        working-directory: appinventor
      - name: 'Build Appinventor'
        run: ant noplay
        working-directory: appinventor
      - name: 'Run Tests'
        run: ant tests
        working-directory: appinventor

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GIGET_AUTH }}

      - name: Push Docker Image
        run: |
          IMAGE=ghcr.io/ekalavya-io/ekalavya-appinventor-sources:${{ env.TAG }}
          docker build -f Dockerfile -t $IMAGE .
          docker push $IMAGE